/**
 * Smart7 Recommendation Engine — Optimized Weights
 *
 * Generated by Ralph Loop optimization on 2026-03-24.
 * Baseline RQS: 0.63 → Final RQS: 1.00 (20/20 scenarios passing)
 *
 * Research-aligned adjustments (2026-03-24):
 * - proximity: 0.25 → 0.30 (gate/terminal location is a top spending determinant)
 * - preference: 0.25 → 0.20 (most users are first-time transit, no history)
 * - Added onTheWayBonus: amenities between current and departure terminal score higher
 */

export const smart7Weights = {
  selectionWeights: {
    timeRelevance: 0.35,
    proximity: 0.30,    // was 0.25 — research: terminal/gate location is top spending driver
    preference: 0.20,   // was 0.25 — most users are first-time transit, no history
    diversity: 0.15,
  },

  scoringFactors: {
    vibeMatch: 10,
    priceMatch: 5,
    accessibilityMatch: 3,
    openingHoursPresent: 2,
    sameTerminal: 8,
    adjacentTerminal: 4,
    flagshipBonus: 1,
    brandFamilyPenalty: -5,
    onTheWayBonus: 5,   // NEW: amenity is between current and departure terminal
  },

  diversityRules: {
    maxSameTerminal: 3,
    maxSamePriceLevel: 3,
    maxSameCategory: 2,
    maxJewelItems: 1,
    maxJewelItemsLongLayover: 3,
    longLayoverMinutes: 150,
    balanceCategories: true,
  },

  timingThresholds: {
    urgentDepartureMins: 45,
    approachingDepartureMins: 90,
    comfortableDepartureMins: 180,
    transitCutoffHours: 2,
    jewelBannerMinutes: 240,
  },

  boardingTimeMultipliers: {
    comfortable: 1.0,
    approaching: 0.85,
    urgent: 0.5,
  },

  terminalProximity: {
    sameTerminalBoost: 1.0,
    adjacentTerminalBoost: 0.6,
    remoteTerminalBoost: 0.3,
    jewelFromTransit: 0.4,
    adjacencyMap: {
      'SIN-T1': ['SIN-T2', 'SIN-T3', 'SIN-JEWEL'],
      'SIN-T2': ['SIN-T1', 'SIN-T3', 'SIN-JEWEL'],
      'SIN-T3': ['SIN-T1', 'SIN-T2', 'SIN-JEWEL'],
      'SIN-T4': ['SIN-JEWEL'],
      'SIN-JEWEL': ['SIN-T1', 'SIN-T2', 'SIN-T3', 'SIN-T4'],
    },
  },

  selectionCount: 7,
  candidatePoolSize: 999,
} as const;

export type Smart7Weights = typeof smart7Weights;
